## Exploratory Data Analysis (EDA) Madrid

En este ejercicio vamos a utilizar el excel **`DatosMadrid.xlsx`**, este excel contiene información sobre los distritos y barrios de Madrid.

Para esta actividad vamos a explorar el **`DataFrame`**, veamos que tipo de información tiene y luego vamos a generar visualizaciones que represente la información del **`DataFrame`**.

Este ejercicio es libre, es decir, puedes decidir que información poner en las visualizaciones y cuantas quieres hacer, la idea es realizar un **`EDA`** y entender los datos con los que estamos trabajando.

Prueba creando tus propios atributos utilizando la información del **`DataFrame`**.

Escribe en un documento (o en el notebook) una lista de todas las graficas que quieres hacer y lo que representan, como por ejemplo:<br> **`El número de personas mayores de 65 por barrio o municipio`**.

Durante este proceso lo más probable es que consigas valores atípicos (**outliers**) y/o valores faltantes (**NaN's**).

Al final del ejercicios explica las gráficas y tus hallazgos/conclusiones.

In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

import matplotlib.pyplot as plt
import seaborn as sns

import folium

In [2]:
df = pd.read_excel("data/DatosMadrid.xlsx")

df.head()

,Municipio,Distrito,Barrios,Población,0-15 años,16-64 años,65 o más años,Edad promedio,Densidad,Superficie,Índice de la estructura de la población activa,Tasa de desempleo,Nacimientos,Defunciones,Inmigración,Emigración,Renta neta media anual de los hogares\n,Actividades economicas,Educacion,Centros Universitarios,Sanidad,Bibliotecas,"Instalaciones deportivas(Polideportivos, no básicas",Zonas verdes (m2),Latidud,Longitud,Distancia al centro (km),Metro,Tren,Autobus,Calidad del aire,"PM2,5",PM10,NO2,O3,SO2,Monumentos,Ocio/cultura,Residuos generados,Seguridad Percibida día,Seguridad Percibida de Noche,Delitos intervencion policial,Delitos contra seguridad vial,Precio feb 2021,Variación mensual,Variación trimestral,Variación anual,Máximo histórico(precio),Satisfacción de vivir en su barrio \n,Calidad de vida actual en su barrio \n
0,Madrid,Centro,NaN,140991,10919,107548,22006,43.89,261.823804,5.228,101.47,9.24,967,1048,15015,5556,39613.0,11131,258,3,161,5.0,2,378927.0,NaN,NaN,NaN,NaN,NaN,NaN,Muy bueno,0-10,0-20,0-100,0-80,0-40,370,835.0,76850,82.7,69.8,1936,309,4830.0,-0.200,-1.000,-5.100,5096.0,77.3,73.6
1,Madrid,Centro,Palacio,23695,1825,17342,4426,45.78,161.190476,1.470,85.14,10.25,154,192,2022,864,35509.2,1615,53,0,19,1.0,0,287039.0,40.41513,-3.71562,1.049016,1.0,0.0,1.0,Muy bueno,0-10,0-20,0-100,0-80,0-40,143,140.0,12915,82.7,69.8,325,52,4764.0,-0.100,0.008,0.018,5073.0,77.3,73.6
2,Madrid,Centro,Embajadores,47224,3914,36697,6437,42.69,457.596899,1.032,108.04,10.79,337,344,5129,2048,26762.0,2844,71,2,37,2.0,0,40198.0,40.40968,-3.70164,0.821903,1.0,1.0,1.0,Muy bueno,0-10,0-20,0-100,0-80,0-40,37,279.0,25740,82.7,69.8,648,104,4162.0,0.000,-1.700,-7.300,4489.0,77.3,73.6
3,Madrid,Centro,Cortes,10793,772,8191,1808,44.78,182.314189,0.592,96.43,8.11,74,86,1210,440,37427.0,115,24,1,15,0.0,0,6959.0,40.41435,-3.69853,0.510682,1.0,0.0,1.0,Muy bueno,0-10,0-20,0-100,0-80,0-40,66,64.0,5883,82.7,69.8,148,24,5229.0,0.015,0.030,-2.100,5481.0,77.3,73.6
4,Madrid,Centro,Justicia,18092,1419,13775,2827,44.09,243.827493,0.742,96.59,7.95,129,122,2005,672,41584.0,1817,31,0,28,1.0,2,22422.0,40.42396,-3.69575,1.018647,1.0,0.0,1.0,Muy bueno,0-10,0-20,0-100,0-80,0-40,41,107.0,9862,82.7,69.8,248,40,5707.0,0.012,-1.700,-1.700,6120.0,77.3,73.6

In [8]:
df.drop(df._get_numeric_data().columns, axis = 1)

,Municipio,Distrito,Barrios,Calidad del aire,"PM2,5",PM10,NO2,O3,SO2
0,Madrid,Centro,NaN,Muy bueno,0-10,0-20,0-100,0-80,0-40
1,Madrid,Centro,Palacio,Muy bueno,0-10,0-20,0-100,0-80,0-40
2,Madrid,Centro,Embajadores,Muy bueno,0-10,0-20,0-100,0-80,0-40
3,Madrid,Centro,Cortes,Muy bueno,0-10,0-20,0-100,0-80,0-40
4,Madrid,Centro,Justicia,Muy bueno,0-10,0-20,0-100,0-80,0-40
...,...,...,...,...,...,...,...,...,...
147,Madrid,Barajas,Alameda de Osuna,Muy bueno,0-10,0-20,0-100,0-80,0-40
148,Madrid,Barajas,Aeropuerto,Muy bueno,0-10,0-20,0-100,0-80,0-40
149,Madrid,Barajas,Casco Histórico de Barajas,Muy bueno,0-10,0-20,0-100,0-80,0-40
150,Madrid,Barajas,Timón,Muy bueno,0-10,0-20,0-100,0-80,0-40
151,Madrid,Barajas,Corralejos,Muy bueno,0-10,0-20,0-100,0-80,0-40