## MySQL - Subqueries (Subconsultas)

Una subquery es una consulta SQL que se encuentra dentro de otra consulta SQL. Las subqueries pueden ser muy útiles para realizar operaciones complejas y para obtener datos que dependen de otros datos.

Las subqueries pueden aparecer en varias partes de una consulta, incluyendo el **SELECT**, **FROM**, **WHERE** y **HAVING** de una consulta SQL. Dependiendo de dónde aparezcan en la consulta, las subconsultas pueden ser de un solo valor (devuelven un solo valor) o de varios valores (devuelven una lista de valores).

1. **Encontrar películas con una duración superior al promedio**:

    ```sql
    SELECT 
        title, length
    FROM
        film
    WHERE
        length > (SELECT 
                AVG(length)
            FROM
                film);
    ```

    Esta consulta devolverá todas las películas cuya duración es superior al promedio.


2. **Encontrar clientes que han alquilado una película específica**:

    ```sql
    SELECT 
        customer_id
    FROM
        rental
    WHERE
        inventory_id IN (SELECT 
                inventory_id
            FROM
                inventory
            WHERE
                film_id = 1);
    ```

    Esta consulta devolverá todos los clientes que han alquilado la película con el id 1.
    

3. **Encontrar el número de películas por categoría**:

    ```sql
    SELECT 
        name,
        (SELECT 
                COUNT(*)
            FROM
                film_category
            WHERE
                category_id = category.category_id) AS number_of_films
    FROM
        category;
    ```

    Esta consulta devolverá el nombre de cada categoría y el número de películas en esa categoría.
    

4. **Encontrar la película más larga de cada categoría**:

    ```sql
    SELECT 
        category_id,
        (SELECT 
                title
            FROM
                film
            WHERE
                film_id = (SELECT 
                        film_id
                    FROM
                        film_category
                    WHERE
                        category_id = category.category_id
                    ORDER BY length DESC
                    LIMIT 1)) AS longest_film
    FROM
        category;
    ```

    Esta consulta devolverá el id de cada categoría y el título de la película más larga en esa categoría.
    

5. **Encontrar el total de ingresos de cada tienda**:

    ```sql
    SELECT 
        store_id,
        (SELECT 
                SUM(amount)
            FROM
                payment
            WHERE
                customer_id IN (SELECT 
                        customer_id
                    FROM
                        customer
                    WHERE
                        store_id = store.store_id)) AS total_revenue
    FROM
        store;
    ```

In [ ]:
################################################################################################################################