## MySQL - Funciones para Texto

En SQL podemos usar funciones para manipulación y limpieza de texto.


- **LENGTH**
- **POSITION**
- **REGEXP**
- **CONCAT**
- **SUBSTRING**

### Funciones

#### LENGTH()

- **`LENGTH()`** se utiliza para obtener la longitud de una cadena.

**Sintaxis:**
```sql
LENGTH(string)
```

- **Ejemplos**:

1. **Obtener la longitud de una cadena simple**:

    ```sql
    SELECT LENGTH('Hola Mundo');
    ```
    
2. **Obtener la longitud de una columna de texto**:

    ```sql
    SELECT 
        first_name, LENGTH(first_name) AS longitud_nombre
    FROM
        customer;
    ```
    
3. **Usar la función LENGTH en la cláusula WHERE**:

    ```sql
    SELECT 
        first_name
    FROM
        customer
    WHERE
        LENGTH(first_name) > 5;
    ```

#### POSITION()

- **`POSITION()`** se utiliza para encontrar la posición de la primera aparición de una subcadena en una cadena. Similar a **`.find()`** o **`.index()`** en Python.

**Sintaxis:**
```sql
POSITION(substring IN string)
```
Donde **substring** es la subcadena que quieres encontrar y **string** es la cadena en la que quieres buscar.

- **Ejemplos:**

1. **Encontrar la posición de una subcadena en una cadena simple**:

    ```sql
    SELECT POSITION('Mundo' IN 'Hola Mundo');
    ```
    
2. **Encontrar la posición de una subcadena en una columna de texto**:

    ```sql
    SELECT 
        first_name, POSITION('a' IN first_name) AS posicion_a
    FROM
        customer;
    ```
    
3. **Usar la función POSITION en la cláusula WHERE**:

    ```sql
    SELECT 
        first_name
    FROM
        customer
    WHERE
        POSITION('a' IN first_name) = 2;
    ```

#### REGEX()

- **`REGEX()`** se utiliza en una cláusula WHERE para buscar un patrón específico en una columna utilizando expresiones regulares.

| Metacaracter | Descripción                                                                                                 |
|--------------|-------------------------------------------------------------------------------------------------------------|
| `.`          | Coincide con cualquier carácter individual.                                                                 |
| `^`          | Coincide con el inicio de la cadena.                                                                        |
| `$`          | Coincide con el final de la cadena.                                                                         |
| `*`          | Coincide con cero o más instancias del carácter anterior.                                                   |
| `+`          | Coincide con una o más instancias del carácter anterior.                                                    |
| `?`          | Coincide con cero o una instancia del carácter anterior.                                                    |
| `{n}`        | Coincide exactamente con `n` instancias del carácter anterior.                                              |
| `{n,}`       | Coincide con `n` o más instancias del carácter anterior.                                                    |
| `{n,m}`      | Coincide con al menos `n` y no más de `m` instancias del carácter anterior.                                 |
| `[]`         | Define una clase de caracteres. Coincide con cualquier carácter dentro de los corchetes.                    |
| `[^]`        | Define una clase de caracteres negada. Coincide con cualquier carácter que no esté dentro de los corchetes. |
| `()`         | Define un grupo de caracteres.                                                                              |
| `\`          | Escapa el carácter siguiente, anulando su significado especial.                                             |
| `\|`          | Actúa como un operador OR. Coincide con el patrón antes o después del `\|`.                                |
| `-`          | Define un rango de caracteres en una clase de caracteres.                                                   |

MySQL usa POSIX regex, que puede tener algunas diferencias con otros regex.

**Sintaxis:**
```sql
column REGEXP pattern
```

1. **Encontrar clientes cuyos nombres empiezan con una vocal**:

    ```sql
    SELECT 
        *
    FROM
        customer
    WHERE
        first_name REGEXP '^[AEIOU]';
    ```

2. **Encontrar clientes cuyos nombres terminan con una vocal**:

    ```sql
    SELECT 
        *
    FROM
        customer
    WHERE
        first_name REGEXP '[AEIOU]$';

    ```
    
3. **Encontrar clientes cuyos nombres tienen exactamente 5 caracteres**:

    ```sql
    SELECT 
        *
    FROM
        customer
    WHERE
        first_name REGEXP '^.....$';
    ```

#### CONCAT()

- **`CONCAT()`** se utiliza para concatenar dos o más cadenas de texto en una sola cadena.

**Sintaxis**:

```sql
CONCAT(string1, string2, ..., stringN);
```

Donde **string1**, **string2**, ..., **stringN** son las cadenas que se van a concatenar.

- **Ejemplos:**

1. **Concatenar dos cadenas simples**:

    ```sql
    SELECT CONCAT('Hola', ' Mundo');
    ```
    
2. **Concatenar los nombres y apellidos de los customers**:

    ```sql
    SELECT 
        CONCAT(first_name, ' ', last_name) AS nombre_completo
    FROM
        customer;
    ```
    
3. **Usar la función CONCAT en la cláusula WHERE**:

    ```sql
    SELECT 
        *
    FROM
        customer
    WHERE
        CONCAT(first_name, ' ', last_name) = 'MARY SMITH';
    ```

#### SUBSTRING()

- **`SUBSTRING()`** se utiliza para extraer una subcadena de una cadena.

**Sintaxis:**

```sql
SUBSTRING(string, start, length)
```

Donde **string** es la cadena de la que quieres extraer, **start** es la posición donde quieres empezar a extraer, y **length** es el número de caracteres que quieres extraer. Si **length** es negativo extrae los caractéres empezado por la derecha.

- **Ejemplos:**

1. **Extraer los primeros 5 caracteres de una cadena**:

    ```sql
    SELECT SUBSTRING('Hello World', 1, 5);
    ```

2. **Extraer los últimos 5 caracteres de una cadena**:

    ```sql
    SELECT SUBSTRING('Hello World', -5);
    ```

3. **Extraer los primeros 5 caracteres del nombre de cada cliente**:

    ```sql
    SELECT 
        SUBSTRING(first_name, 1, 5) AS short_name
    FROM
        customer;
    ```

In [ ]:
################################################################################################################################